описания+фетчеры
sno-mephi/snomephi_bot pull request #13
Opened 2023-11-25 14:51 UTC by ViktorovaA

добавлено описание к LastUserActionType
добавлены название и описание к UserRole
добавлены команды USER_INFO, ROLE_DESCRIPTION в TextCommands
+RoleDescriptionFetcher
+UserInfoFetcher

2023-11-25 17:18 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/UserInfoFetcher.kt
> +    }
лучше использовать конструкции типа
```kotlin
val messageText = "ФИО: $fullName"
```

2023-11-25 17:19 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/data/enums/UserRole.kt
название

2023-11-27 09:11 UTC, idfedorov09 requested changes

2023-11-27 09:11 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/data/enums/LastUserActionType.kt
> +    val actionDescription: String,
лучше просто `description`, и так понятно что оно относится к последнему действию

2023-11-27 09:11 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/UserInfoFetcher.kt
> +            else -> user.lastUserActionType.actionDescription
давай просто значение енама записывать? Тогда поле `actionDescription` можно вообще выпилить

2023-11-27 09:11 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/data/enums/TextCommands.kt
> +        "Тестовая команда 2",
🤔

2023-11-27 09:11 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/data/enums/UserRole.kt
> +    /** описание роли **/
не описание, а название хд

2023-11-27 09:11 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/data/enums/UserRole.kt
> +    val roleName: String,
давай тут тоже префикс `role` опустим везде? И roleName удалим, будем просто строковое представление значение енама делать (также как предложено в комментах выше)

2023-11-27 09:11 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/RoleDescriptionFetcher.kt
> +        if (TextCommands.isTextCommand(messageText)) {
тут фетчер про обработку команд же? если так то где-то выше кажется лучше прописать что-то типа
```kotlin
if (!TextCommands.isTextCommand(messageText)) return
```
чтобы не получился у нас однажды callback hell)

2023-11-27 09:11 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/RoleDescriptionFetcher.kt
> +                }
а можно просто
```kotlin
val text = UserRole.values().joinToString("\n\n") {
    "- ${it.roleName}\n\t${it.roleDescription}"
}
```
кажется так лучше читается. Давай так сделаем? И постараемся как можно меньше `var`-ов плодить в будущем

2023-11-27 09:11 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/RoleDescriptionFetcher.kt
> +class RoleDescriptionFetcher(
можно сюда коммент подписать с описанием что делает фетчер?
и надо бы его в граф пихнуть куда-нибудь) но это потом, так как есть еще такая штука как диалог, надо бы удобно проверять идет ли щас диалог или нет.. короче я сделаю

2023-11-27 09:11 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/UserInfoFetcher.kt
> +            bot = bot,
чтобы `bot` не тащить туда-сюда, можно его заинжектить в конструктор класса. Давай так сделаем?

2023-11-27 09:11 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/UserInfoFetcher.kt
> +class UserInfoFetcher(
давай назовем как-то вроде `UserInfoCommandFetcher`, чтобы было понятно что речь про команду, а не про что-нибудь другое?

2023-11-27 09:11 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/UserInfoFetcher.kt
> +            if (TextCommands.USER_INFO.isAllowed(params.userActualizedInfo)) {
хохо, почти callback hell
давай снова ту же схему? return если нет команды и следующее после него условие проверяет что команда запрещена. Если успешно то выводим сообщение и return,  а далее весь остальной код?

2023-11-27 09:11 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/UserInfoFetcher.kt
> +                }
вот этот `when` лучше на `if else` заменить. И давай проверять не сплитами, а регуляркой?

2023-11-27 09:11 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/UserInfoFetcher.kt
> +        )
`format` чет так и остался, ты точно пушила изменения?
напомню, давай лучше сделаем что-то типа
```kotlin
msg.text = "ФИО: $fullName" // .. и тд
```

2023-12-02 09:08 UTC, idfedorov09 approved these changes

2023-12-02 12:55 UTC, andromedagalua approved these changes

2023-12-02 12:55 UTC, andromedagalua commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/RoleDescriptionFetcher.kt
> +        if (!TextCommands.isTextCommand(messageText)) return
как-будто лишнее условие, но ок

2023-12-02 12:56 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/RoleDescriptionFetcher.kt
> +        if (!TextCommands.isTextCommand(messageText)) return
> как-будто лишнее условие, но ок

поч?

2023-12-02 13:09 UTC, andromedagalua commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/RoleDescriptionFetcher.kt
> +        if (!TextCommands.isTextCommand(messageText)) return
> > как-будто лишнее условие, но ок
> 
> поч?

ну а зачем проверять что это не команда
если ты потом проверяешь что это команда юзеринфор

2023-12-02 13:40 UTC, ViktorovaA commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/RoleDescriptionFetcher.kt
> +        if (!TextCommands.isTextCommand(messageText)) return
переделала

2023-12-02 16:26 UTC, idfedorov09 approved these changes

2023-12-02 16:26 UTC, merged