registration
sno-mephi/snomephi_bot pull request #14
Opened 2023-11-25 20:20 UTC by Tanexc

2023-11-25 22:52 UTC, andromedagalua requested changes

2023-11-25 22:52 UTC, andromedagalua commented on src/main/java/ru/idfedorov09/telegram/bot/util/Validator.kt
> +    it.isNotEmpty() && "([МСБмсб]{1})([0-9]{2})-([0-9]{3})".toRegex().matches(it)
аспирантов забыли

2023-11-25 22:52 UTC, andromedagalua commented on src/main/java/ru/idfedorov09/telegram/bot/config/Constants.kt
мб через enum сделать?

2023-11-25 22:52 UTC, andromedagalua commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/registrationFetcher/RegistrationFetcher.kt
> +            user.fullName -> {
Добавить подтверждение имени?
т.е. защита от того, что случайное сообщение станет именем

2023-11-26 11:10 UTC, vSEK1RO commented
1. Бот ложится после редактирования сообщения (в котором была введена неправильная группа)
2. Мне кажется что к одному аккаунту телеги должен быть привязан только 1 аккаунт в боте, иначе какой смысл от регистрации, любой человек сможет залогиниться с твоего акка

2023-11-27 00:55 UTC, closed without merging