Registration fix
sno-mephi/snomephi_bot pull request #15
Opened 2023-11-27 01:02 UTC by Tanexc

Изменения:

- сообщения для регистрации теперь enum, а не const val как раньше
- добавил кнопочки для подтверждения имени/группы
- пофиксил вылеты при редактировании сообщения/при слишком длинном сообщении
- теперь нельзя создать нового пользователя с именем и группой, если кто-то под таким именем и группой уже зарегистрирован

2023-11-27 08:42 UTC, idfedorov09 requested changes

2023-11-27 08:42 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/user_fetchers/UserActionHandlerFetcher.kt
> +                .getOrElse { return }
можно просто `update.hasCallbackQuery()` проверить, так кажется более читаемо

2023-11-27 08:42 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/user_fetchers/UserActionHandlerFetcher.kt
> +                    this.text = message.text
`this` можно опустить, не оч выглядит. Ну или если хочется прям выделить, что для EditMessageText() проставляешь значения, то лучше через `let` и `it`

2023-11-27 08:42 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/util/Validator.kt
> +} ?: false
это же по одному разу используется в коде? мб тогда не будем выносить в util?

2023-11-27 08:42 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/flow/TelegramBotFlowConfiguration.kt
> +//            }
зачем закомментил?) регистрацию надо бы сделать так, чтобы она с этим работала. Ну или добавить в exp признак зареган юзер или нет, и в графе явно прописать

2023-11-27 08:42 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/flow/TelegramBotFlowConfiguration.kt
> +                fetch(registrationFetcher)
давай все же это будет идти после actualizeUserInfoFetcher?
Вкратце тут расскажу, че происходит: если пользователя нет в бд то создается новая запись прямо там же, потом в контекст кладется UserActualizedInfo. В принципе, по нему можно понять, зареган пользователь или нет. Далее прогняется граф, во время его выполнения  этот UserActualizedInfo может как-то измениться, и измененная версия уже сохраняется в бдшке последним фетчером (updateDataFetcher).
Давай лучше от этого исходить, чем с голыми данными работать?

2023-11-27 08:42 UTC, idfedorov09 commented on gradlew
> +
спасибо

2023-11-27 08:42 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/user_fetchers/UserActionHandlerFetcher.kt
> +class UserActionHandlerFetcher(
прямо все действия юзера хочешь тут обрабатывать? Мб лучше именно действия незареганных юзеров? Если так то тогда нейминг)

2023-11-27 08:42 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/user_fetchers/RegistrationFetcher.kt
> +class RegistrationFetcher(
тут же не вся логика регистрации собрана? Давай чуть более говорящее название дадим

2023-12-01 16:22 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/user_fetchers/RegistrationFetcher.kt
> +class RegistrationFetcher(
> тут же не вся логика регистрации собрана? Давай чуть более говорящее название дадим

ну так то вся логика регистрации тут, кроме обработки нажатия на кнопочки, хз какое название еще можно сюда бахнуть

2023-12-01 16:26 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/flow/TelegramBotFlowConfiguration.kt
> +                fetch(registrationFetcher)
ок ок

2023-12-01 17:27 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/flow/TelegramBotFlowConfiguration.kt
> +//            }
закомментил потому что бот падает после регистрации. Добавил флаг в ехр указывающий зареган пользователь или нет. Если тип зарегался, то из-за его следующего сообщения бот ложится. проблемы в questStartFetcher (в логе выдает Caused by: Error executing org.telegram.telegrambots.meta.api.methods.send.SendMessage query: [400] Bad Request: chat not found), чел кто это писал пытается найти chat с chatId = tui юзера. Думаю, не я должен это фиксить

2023-12-01 17:33 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/user_fetchers/UserActionHandlerFetcher.kt
> +class UserActionHandlerFetcher(
поменял

2023-12-01 17:34 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/util/Validator.kt
> +} ?: false
поменял

2023-12-01 17:34 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/user_fetchers/UserActionHandlerFetcher.kt
> +                    this.text = message.text
убрал

2023-12-01 17:34 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/user_fetchers/UserActionHandlerFetcher.kt
> +                .getOrElse { return }
поменял

2023-12-02 08:40 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/user_fetchers/UserActionHandlerFetcher.kt
> +                .getOrElse { return }
> поменял

кнопочка `Resolve conversation`

2023-12-02 08:43 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/flow/TelegramBotFlowConfiguration.kt
> +//            }
> закомментил потому что бот падает после регистрации. Добавил флаг в ехр указывающий зареган пользователь или нет. Если тип зарегался, то из-за его следующего сообщения бот ложится. проблемы в questStartFetcher (в логе выдает Caused by: Error executing org.telegram.telegrambots.meta.api.methods.send.SendMessage query: [400] Bad Request: chat not found), чел кто это писал пытается найти chat с chatId = tui юзера. Думаю, не я должен это фиксить

не-не, все ок, там скорее бот пытается написать в админскую беседу, чтобы создать обращение
ее айдишник где-то в коде прописан, так что все ок. Чуть позже его вынесем в проперти

2023-12-02 09:02 UTC, idfedorov09 requested changes

2023-12-02 09:02 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/user_fetchers/RegistrationActionHandlerFetcher.kt
> +package ru.idfedorov09.telegram.bot.fetchers.bot.user_fetchers
давай следовать [google java style](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names)? В соответствии с ним, `ru.idfedorov09.telegram.bot.fetchers.bot.user_fetchers` недопустимо, давай лучше сделаем `ru.idfedorov09.telegram.bot.fetchers.bot.userfetchers`

2023-12-02 09:02 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/user_fetchers/RegistrationActionHandlerFetcher.kt
> +        user: User,
опять же, давай использовать `userActualizedInfo`?

2023-12-02 09:02 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/user_fetchers/RegistrationFetcher.kt
> +            user.fullName == "n/a" -> {
давай лучше использовать `lastUserActionType` вместо этого? Чтобы подобные имена в бд не висели

2023-12-02 09:02 UTC, idfedorov09 commented
Не забывай плиз про `Resolve conversation`, если поправил что-то

2023-12-07 11:57 UTC, andromedagalua commented on src/main/java/ru/idfedorov09/telegram/bot/data/enums/UserStrings.kt
> +enum class UserStrings(private val text: String) {
Название как-будто неудачное

2023-12-08 21:24 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/data/enums/UserStrings.kt
> +enum class UserStrings(private val text: String) {
Что предлагаете?

2023-12-08 21:30 UTC, vSEK1RO approved these changes
Approved

2023-12-08 21:30 UTC, vSEK1RO commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/userfetchers/RegistrationActionHandlerFetcher.kt
> +        var user = userInfo
Передавай аргументы через request data

2023-12-08 21:30 UTC, vSEK1RO commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/userfetchers/RegistrationFetcher.kt
> +                userRepository.findByFullNameAndStudyGroup(userInfo.fullName ?: "", message.text)?.run {
вынести в отдельные приватные функции внутри фетчера

2023-12-08 21:48 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/userfetchers/RegistrationActionHandlerFetcher.kt
> +        var user = userInfo
нужно мне кажется это выделить в отдельный класс в модельных тогда, обсудим с остальными

2023-12-08 21:48 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/userfetchers/RegistrationFetcher.kt
> +                userRepository.findByFullNameAndStudyGroup(userInfo.fullName ?: "", message.text)?.run {
может быть так и будет лучше

2023-12-09 17:17 UTC, andromedagalua commented on src/main/java/ru/idfedorov09/telegram/bot/data/enums/UserStrings.kt
> +enum class UserStrings(private val text: String) {
Ну я как понимаю enum нужен чтобы хранить там все текстовые сообщения
ну, а UserString как-будто не об этом
какой-нибудь TextMessage

2023-12-22 17:23 UTC, andromedagalua requested changes

2023-12-22 17:23 UTC, andromedagalua commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/userfetchers/RegistrationFetcher.kt
> +        it.isNotEmpty() && it.length < 80
оставь только кириллицу, латиницу и пробелы, убери все спецсимволы и цифры

2023-12-22 18:37 UTC, merged