Бан и разбан пользователей
sno-mephi/snomephi_bot pull request #16
Opened 2023-12-02 16:48 UTC by lux-hacker

Добавлен механизм бана и разбана пользователей

Эти операции может делать только ROOT

2023-12-08 21:40 UTC, vSEK1RO commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/BanUserFetcher.kt
> +            if (user == null) {
nullsafety?

2023-12-08 21:41 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/repo/BanRepository.kt
> +    @Query("SELECT a FROM Ban a WHERE a.userId = :user_id ")
Кажется jpa может создать findByUserId без использования аннотаций, если передавать в функцию параметр названный так же как и в функции

2023-12-08 21:42 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/UnbanUserFetcher.kt
> +            if (user == null) {
можно и null safety заюзать чтоб по кайфу было, тогда user будет просто не типа User?, а User

2023-12-09 11:32 UTC, idfedorov09 requested changes

2023-12-09 11:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/data/model/Ban.kt
> +    val comment: String? = null,
может лучше `reason`?

2023-12-09 11:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/BanUserFetcher.kt
> +        val msg = updatesUtil.getText(update)
да кста, `getText()` щас лучше не юзать, там с кодировкой рофлы могут случиться, лучше просто`update.message.text`

2023-12-09 11:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/UnbanUserFetcher.kt
> +            if (user == null) {
у меня ощущение, что тут с логикой что-то не то
это же не должно работать..

2024-02-25 13:52 UTC, closed without merging