Category: удаление, создание, изменение
sno-mephi/snomephi_bot pull request #18
Opened 2023-12-08 20:47 UTC by vSEK1RO

# Меню выбора действия с категорией /category
![image](https://github.com/sno-mephi/snomephi_bot/assets/114253920/9b32dbb7-0cfb-4280-9981-03b107f67a89)
# Пагинация категорий (для изменения и удаления
![image](https://github.com/sno-mephi/snomephi_bot/assets/114253920/452c09ae-8cb9-48c2-803f-f9edb50355cd)
# Окно подтвердждения
![image](https://github.com/sno-mephi/snomephi_bot/assets/114253920/0ea88869-71bc-4fe7-929a-e28cd18f14d6)
# Последовательность ввода категории (с возможностью прерывания путем коллбэка кнопки отмена) + проверка на корректность введенных данных
![image](https://github.com/sno-mephi/snomephi_bot/assets/114253920/8775543d-8483-4a7d-84c1-b3bff384214f)

2023-12-08 21:11 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/data/keyboards/CategoryKeyboards.kt
> +            val nav=choosingCategoryNav(page,pageSize,catRep)
Протыкай пж ctrl+alt+L отфармотируй код по ktlint :)

2023-12-08 21:16 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/CategoryActionTypeHandlerFetcher.kt
> +    private data class RequestData(
мне кажется стоит это убрать в моделки бизнес логики, мб кто то захочет это тоже юзать

2023-12-08 21:16 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/flow/TelegramBotFlowConfiguration.kt
> +            fetch(testFetcher)
надо бы убрать наверно этот тест фетре

2023-12-08 21:30 UTC, Tanexc approved these changes

2023-12-08 22:32 UTC, idfedorov09 requested changes

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/SnoBotHandlerApplication.java
> +	//
?

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/data/keyboards/CategoryKeyboards.kt
> +        fun choosingAction(): InlineKeyboardMarkup {
ну да понимаю похоже что `companion object` это типа как `static` в джаве, поэтому почему бы не сделать так, но обычно все же если требуется что-то только со статическими полями, то вместо `class` создают `object` и внутри него уже просто пихают поля, типа как тут https://github.com/sno-mephi/snoxi_bot/blob/main/src/main/java/ru/idfedorov09/telegram/bot/util/MessageUtils.kt

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/data/model/Category.kt
> +    val changingByTui: String? = null,
как будто мисматч между комментом и именем поля)

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/CategoryActionTypeHandlerFetcher.kt
> +    private data class RequestData(
да не, норм

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/CategoryActionTypeHandlerFetcher.kt
> +    private data class RequestData(
такие штуки не так часто используются на самом деле, и обычно они под разные ситуации отличаются

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/CategoryActionTypeHandlerFetcher.kt
> +                return userActualizedInfo
как будто это лишнее

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/CategoryActionTypeHandlerFetcher.kt
> +                CategoryKeyboards.inputCancel(),
может тогда сообщим максимально возможную длину сообщения?

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/CategoryActionTypeHandlerFetcher.kt
> +        if (!messageText.matches(Regex("^[a-zа-я0-9_]+$"))) {
давай сделаем суффикс только латиницей/цифрами/нижними подчеркиваниями? а то будут у нас команды типа
```
/toggle_пробный_коллоквиум
```
что выглядит не очень из-за смешивания языков

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/CategoryActionTypeHandlerFetcher.kt
> +        if (messageText.length > 255) {
ну для описания можно и побольше символов зарезервировать, скажем штук 500-700

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/CategoryButtonHandlerFetcher.kt
> +    }
как будто это можно в один метод пихнуть

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/CategoryActionTypeHandlerFetcher.kt
> +            return
мб просто на кнопку попросим нажать? Кажется так в разы удобнее

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/CategoryCommandHandlerFetcher.kt
> +    }
может без этих методов не обойдемся? они кажется уже в 3м фетчере мелькают, ладно там в больших, но тут будто и без них можно справиться - по одному вызову

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/QuestButtonHandlerFetcher.kt
> +        bot.execute(AnswerCallbackQuery(update.callbackQuery.id))
оп, а тут я предлагаю просто это пихнуть в последний фетчер - тогда answer прилетит точно после обработки апдейта) красивенько будет

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/flow/TelegramBotFlowConfiguration.kt
> +            fetch(testFetcher)
согласен

2023-12-08 22:32 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/flow/TelegramBotFlowConfiguration.kt
> +//            }
эти фетчеры подружить не удалось? если нет то ок, сделаю

2023-12-08 22:36 UTC, vSEK1RO commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/CategoryActionTypeHandlerFetcher.kt
> +        if (!messageText.matches(Regex("^[a-zа-я0-9_]+$"))) {
Вроде как попросили добавить русский, но могу вернуть назад если надо

2023-12-08 22:37 UTC, Tanexc commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/CategoryActionTypeHandlerFetcher.kt
> +    private data class RequestData(
а это не антипаттерн получается тогда?

2023-12-08 22:38 UTC, vSEK1RO commented on src/main/java/ru/idfedorov09/telegram/bot/data/model/Category.kt
> +    val changingByTui: String? = null,
Ок, будет changedByTui

2023-12-08 22:40 UTC, vSEK1RO commented on src/main/java/ru/idfedorov09/telegram/bot/flow/TelegramBotFlowConfiguration.kt
> +//            }
Хз, мне чет показалось что они вообще не работают

2023-12-09 13:42 UTC, vSEK1RO commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/CategoryActionTypeHandlerFetcher.kt
> +                return userActualizedInfo
нужно, when должен иметь дефолтное значение в данном случае

2023-12-09 15:07 UTC, vSEK1RO commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/QuestButtonHandlerFetcher.kt
> +        bot.execute(AnswerCallbackQuery(update.callbackQuery.id))
только не в последний, а в первый, пользователь не должен ждать пока фетчеры выполнятся, ответ на кнопку должен сразу прийти чтобы она отвисла

2024-02-01 12:55 UTC, idfedorov09 approved these changes

2024-02-01 12:55 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/data/model/Category.kt
> +    @Column(name = "title", columnDefinition = "VARCHAR(64)")
мб лучше на TEXT поменяем? Мало ли что в будущем поменяется, а лишнии миграции делать не хочется

2024-02-01 12:55 UTC, merged