Настройка рассылки
sno-mephi/snomephi_bot pull request #20
Opened 2024-02-04 16:14 UTC by andromedagalua

2024-03-03 20:18 UTC, vSEK1RO commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/SettingMailFetcher.kt
> +        val mailText = "<b>Настройка уведомлений</b>\n\nВыберите интересующие вас направления:\n\n$allCategoriesInfo"
Нужна проверка если категорий не будет

2024-03-03 20:20 UTC, vSEK1RO commented on src/main/java/ru/idfedorov09/telegram/bot/data/enums/TextCommands.kt
> +        "Настройка рассылки",
команда настройка рассылки, а лейбл сообщения настройка уведомлений

2024-03-03 20:31 UTC, vSEK1RO requested changes
Не работает основной функционал. Независимо от того, является ли категория неснимаемой, пользователь все-равно может отписаться от рассылки

2024-03-04 08:19 UTC, vSEK1RO approved these changes

2024-03-06 02:24 UTC, idfedorov09 requested changes

2024-03-06 02:24 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/ActualizeUserInfoFetcher.kt
> +                roles = mutableSetOf(UserRole.USER, UserRole.ROOT),
АХАХАХАХ, только пофиксили, это щас снова залетит в main, представляю какие рофлы были бы из-за того что это не заметили

2024-03-06 02:24 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/SettingMailFetcher.kt
> +            }
итс окэй, я правда не помню, не будет ли конфликтов с startQuestion

2024-03-06 02:24 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/SettingMailFetcher.kt
> +            userCategories.add(category)
они в бд потом разве сохраняются?

2024-03-09 13:37 UTC, andromedagalua commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/SettingMailFetcher.kt
> +            userCategories.add(category)
в актулайз юзер инфо фетчере сохраняется же

2024-03-09 14:24 UTC, merged