Broadcast service
sno-mephi/snomephi_bot pull request #31
Opened 2024-03-03 18:48 UTC by andromedagalua

закончил Broadcast service

2024-03-03 20:35 UTC, ThePrax12 approved these changes
Norm

2024-03-06 02:06 UTC, idfedorov09 commented
> Norm

окей

2024-03-06 02:17 UTC, idfedorov09 requested changes
Крч ко мне еще одна идея пришла по поводу этого ПРа
Типа если чел делает рассылку СЕЙЧАС то он получает сообщение, что рассылка начата, но если ПЛАНИРУЕТ ее, то не получает
Давай функцию сделаем которая работает как finish но выполняется при старте рассылки? И вообще наверное обсудить этот момент, мб в broadcast_table тогда имеет смысл добавлять поле, нужно ли этот метод запускать или нет, потому что кажется что он не всегда полезен, но это под вопросом

Крч с тебя комменты + потом нужно это обсудить и видимо допилить функционал

2024-03-06 02:17 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/util/BroadcastSenderService.kt
> +import org.jvnet.hk2.annotations.Service
бля братишка))) Что это за хуйня
Потести плиз, как убедишься что все работает - зальем

2024-03-06 02:17 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/util/BroadcastSenderService.kt
> +import org.jvnet.hk2.annotations.Service
Там должен другой пакет портироваться для Service, посмотри в других сервисах (RedisService например)

2024-03-06 02:17 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/util/BroadcastSenderService.kt
> +                    )
все же как-то не оч читается, мб в лямбду вынесем? не нравится мне это чет

2024-03-06 02:17 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/util/BroadcastSenderService.kt
> +                    )
пересечение наобород непусто должно быть, isNotEmpty() юзать надо

2024-03-06 02:17 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/util/BroadcastSenderService.kt
> +    fun sendBroadcast(user: User, broadcast: Broadcast, shouldAddToReceived: Boolean = true) {
Емае.. А что с форматированием
Глаза вырвите плиз

2024-03-06 02:17 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/util/BroadcastSenderService.kt
> +        if (shouldAddToReceived) user.id?.let { broadcast.receivedUsersId.add(it) }
а сохранение в бд не нужно?

2024-03-06 02:17 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/util/BroadcastSenderService.kt
> +        val keyboardList = mutableListOf<List<InlineKeyboardButton>>()
форматирование...

2024-03-06 02:17 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/util/BroadcastSenderService.kt
> +                        it.callbackData = button.callbackData
это будет работать если button.link = null?

2024-03-06 02:17 UTC, idfedorov09 commented
> Norm

как проверял?)

2024-03-06 02:19 UTC, idfedorov09 commented
И еще -- давай-ка не в папку util этот файл, а в service

2024-03-09 14:23 UTC, merged