v1
sno-mephi/snomephi_bot pull request #34
Opened 2024-03-03 21:18 UTC by ThePrax12

вроде испавил баг с тем что бот предлагает регаться челам в беседе. надо потестить

2024-03-04 02:04 UTC, idfedorov09 requested changes

2024-03-04 02:04 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/ActualizeUserInfoFetcher.kt
> +
спасибо

2024-03-04 02:04 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/ActualizeUserInfoFetcher.kt
> +
может локанчинее так?
```kotlin
expContainer.isPersonal = update.message.chatId == tui.toLong()
```

2024-03-04 02:04 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/flow/TelegramBotFlowConfiguration.kt
> +            group(condition = {it.isPersonalUpdate() && it.isByUser() && it.isUserRegistered() }) {
я бы на всякий сначала проверял что оно от пользователя, а только потом что чел зареган или это личное сообщение

2024-03-04 02:04 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/flow/TelegramBotFlowConfiguration.kt
> +    private fun FlowContext.isPersonalUpdate() = get<ExpContainer>()?.isPersonal ?: false
итс окэй

2024-03-04 02:05 UTC, idfedorov09 commented
Поменяй название ПРа пж) И вообще почитай это
https://www.notion.so/6ec825df51d4409fbb1c94fb5541d8f4?pvs=4#87bb8c9ab2a84d4cad2054b5bf249325
как понимаешь, лучше и ПРам давать нормальное название

ЗАЧЕМ ЭТО НУЖНО: да просто чтобы потом легче ориентироваться кто проблемный пр залил)

2024-03-04 18:11 UTC, andromedagalua requested changes
исправь комментарий Ивана Ф.

2024-03-04 18:11 UTC, andromedagalua commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/ActualizeUserInfoFetcher.kt
> +
от души, брат!

2024-03-04 18:11 UTC, andromedagalua commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/ActualizeUserInfoFetcher.kt
> +
пон

2024-03-04 20:09 UTC, andromedagalua approved these changes

2024-03-06 02:05 UTC, idfedorov09 approved these changes
Вот так нельзя было назвать пр?)

2024-03-06 02:06 UTC, merged