SNOM-9315 реализована команда /help, текст в сообщении ещё нужно отредачить
sno-mephi/snomephi_bot pull request #48
Opened 2024-03-11 18:37 UTC by ThePrax12

Реализовал команду /help, вроде всё работает, но у меня нет рута поэтому описание кнопок пока не все готовы, но более менее они есть.

2024-03-12 01:12 UTC, idfedorov09 commented
Рута можно себе выдать в редаше

2024-03-12 01:13 UTC, idfedorov09 commented
..а нет, он снова лежит)

2024-03-12 01:13 UTC, idfedorov09 commented
> Рута можно себе выдать в редаше

.. а нет, он снова лежит) Энивей через запросик можно сделать

2024-03-16 16:25 UTC, andromedagalua approved these changes
говно, но ок

2024-03-16 16:45 UTC, andromedagalua requested changes

2024-03-16 16:45 UTC, andromedagalua commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/HelpCommandFetcher.kt
> +            bot.execute(
мы так больше не делаем!

2024-03-16 16:55 UTC, andromedagalua approved these changes
говно но пойдет

2024-03-16 17:22 UTC, idfedorov09 requested changes

2024-03-16 17:22 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/HelpCommandFetcher.kt
> +            }
joinToString в помощь

2024-03-16 17:22 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/data/model/User.kt
> +    @Column(name = "tui", unique = false)
Убери
`@Column(name = "tui")`

2024-03-16 17:22 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetchers/bot/HelpCommandFetcher.kt
> +            }
```
TextCommands.values().filter { command.isFullCommand && command.allowedRoles.intersect(userActualizedInfo.roles).isNotEmpty() }.joinToString(separator = "\n") {
"▪"+ it.commandText+ " - " + it.description
}
```

2024-03-16 17:25 UTC, idfedorov09 requested changes
поправь комменты пж

2024-03-16 17:48 UTC, idfedorov09 approved these changes

2024-03-16 17:49 UTC, merged